lib/async/http/protocol/http11.rb, spec/async/http/protocol/http11_spec.rb
When requesting an AWS S3 object, some response headers that are returned have numbers in them. So, it seems that numbers are valid in HTTP header names, therefore we allow them.
Fixes #8
=> Allow numbers in HTTP header names

lib/async/http/body/file.rb
It's generally safer to open the file in binary mode, because then C won't try to do any conversions between representations of newlines depending on the OS, it will just retrieve bytes as is. See Avdi's RubyTapas for more details: https://www.rubytapas.com/2016/12/14/ruby-code-on-windows/
=> Open File in binary mode in HTTP::Body::File

lib/async/http/body/buffered.rb, spec/async/http/body/buffered_spec.rb
while using sentry with async faraday adapter I've encountored a bug
```ruby
> Async { Raven.capture { 1/0 } }.wait.result  
Sending event f6b69fac47c042939038275a610f9ac3 to Sentry
Raven HTTP Transport connecting to https://sentry.io
Unable to record event with remote Sentry server (NoMethodError - undefined method `each' for #<String:0x00007f32f02545c0>):
/home/senid/.rvm/gems/ruby-2.5.1@async_rails/gems/async-http-0.38.1/lib/async/http/body/buffered.rb:43:in `for'
/home/senid/.rvm/gems/ruby-2.5.1@async_rails/gems/async-http-0.38.1/lib/async/http/body/buffered.rb:36:in `wrap'
/home/senid/.rvm/gems/ruby-2.5.1@async_rails/gems/async-http-0.38.1/lib/async/http/request.rb:57:in `[]'
/home/senid/.rvm/gems/ruby-2.5.1@async_rails/gems/async-http-0.38.1/lib/async/http/middleware.rb:37:in `block …
```
=> fix Async::HTTP::Body::Buffered.wrap when body is a string

README.md
One of the code samples doesn't run because of an incorrect `require`.
=> Fix `require` in code sample in readme.

lib/async/http/protocol/https.rb
Small fix: should use `raise` instead of `throw` when an error occurs.
There was no test to update.
=> Use raise, not throw.

lib/async/http/relative_location.rb, spec/async/http/relative_location_spec.rb
`ArgumentError` isn't the right error to raise when there are too many redirects because
it indicates that the arguments passed to a method call are wrong.
This is a breaking change. It changes the contract with callers.
=> Change RelativeLocation to raise TooManyRedirects.

async-http.gemspec
This should make it easier for automated tools to find out what license is used.
=> Add licensing information to gemspec.

lib/async/http/relative_location.rb, spec/async/http/relative_location_spec.rb
The number of redirects allowed by the RelativeLocation class was off by
one. A hop is a redirect, but if you passed in 0 hops it wasn't allowing
even a single request. It should have allowed one request but no
redirects.
Also changed the default maximum_hops from 4 to 3 to keep the default
behavior consistent with what it was before.
=> Fix off-by-1 in RelativeLocation.

lib/async/http/protocol/http1/server.rb, spec/async/http/protocol/shared_examples.rb
This PR fixes bug introduced in 5f63e9c: if server tries to respond with `204 No Content` response that does not contain body, following exception is raised:
```
NoMethodError: undefined method `version' for nil:NilClass
/app/lib/async/http/protocol/http1/server.rb:97 in `each'
/app/lib/async/http/server.rb:53 in `accept'
/app/vendor/ruby/2.6.0/gems/async-io-1.29.0/lib/async/io/server.rb:32 in `block in accept_each'
/app/vendor/ruby/2.6.0/gems/async-io-1.29.0/lib/async/io/socket.rb:73 in `block in accept'
/app/vendor/ruby/2.6.0/gems/async-1.25.2/lib/async/task.rb:258 in `block in make_fiber'
```
=> Fix 204 No Content server response

README.md
Hi,
I first wanted to open an issue with a question: "how to set an internet request timeout?". After investigating for some time, I think I got it right so I'm submitting this PR so other's don't have to spend the time.
Here's a more nuanced question:
Is it better to set a timeout directly on [Async::HTTP::Endpoint](https://github.com/bruno-/async-http/blob/timeout_example/lib/async/http/endpoint.rb) instance? Or it's just fine to wrap `Async::HTTP::Internet` requests in a `task.with_timeout` block? Are there any advantages to using low-level `Async::HTTP::Endpoint` directly?
=> Add timeout usage example

lib/async/http/body/pipe.rb, spec/async/http/body/pipe_spec.rb
I watched [your video on transient tasks](https://www.youtube.com/watch?v=tENWCqJXhoI) and realized we have a potential bug when `Body::Pipe` class is used standalone (outside `Proxy` class).
The problem is simple to reproduce and is covered with specs.
```ruby
require 'async'
require 'async/http/body/pipe'
require 'async/http/body/writable'
require 'async/io/socket'
require 'async/io/stream'
Async do
Async::HTTP::Body::Pipe.new(Async::HTTP::Body::Writable.new)
end
```
=> Make Body::Pipe background tasks transient

spec/async/http/proxy_spec.rb
As discussed in Slack, adds some specs to test the "proxy server requires auth, no auth given" case.
After running locally, I'm confirming that the happy path auth succeeds, missing auth gets a broken pipe.
=> Add specs to replicate missing auth.

lib/async/http/body/pipe.rb, spec/async/http/body/pipe_spec.rb
This is another take on the fix proposed in #56.
Hi,
after using `Async::HTTP::Body::Pipe` as pointed out in #55 I started getting these exceptions:
```
0.05s    error: Async::Task [oid=0x8c] [pid=87174] [2020-06-04 16:25:19 +0200]
|   IOError: closed stream
|   → <internal:io> 63
|     /Users/bruno/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.0/lib/async/io/generic.rb:216 in `async_send'
|     /Users/bruno/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.0/lib/async/io/generic.rb:69 in `block in wrap_blocking_method'
|     /Users/bruno/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.0/lib/async/io/stream.rb:261 in `fill_read_buffer'
|     /Users/bruno/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/async-io-1.30.0/lib/async/io/stream.rb:99 in …
```
=> Fix Async::HTTP::Body::Pipe race condition bug

lib/async/http/protocol/http2/connection.rb
Here's a minimal example that illustrates the problem:
```ruby
require "async"
require "async/http/internet"
Async do |task|
internet = Async::HTTP::Internet.new
puts internet.get("https://economist.com/").status # 301, HTTP2 connection
task.sleep 10 # Protocol::HTTP2::GoawayError raised in ~5 seconds as the server closes the connection.
puts "This code unexpectedly runs because the exception was only raised in the background."
puts "The internet object is also fine."
puts internet.get("https://economist.com/").status # 301
end
```
The problem is `Protocol::HTTP2::GoawayError` + its backtrace show up in the terminal whenever the remote server benevolently closes idle connection outside the request-response cycle.
The premise is: this scenario is not an error. It's equivalent to HTTP1 …
=> Don't show HTTP2 GoawayError in terminal

README.md
- Documentation re: https://github.com/socketry/async-http/issues/69
- Note I just added a standalone example without changing the others. I think this is appropriate since this isn't necessarily recommended for all use cases and requires an additional gem. 
- Note I didn't mention that you don't need to call `internet&.close` in an `ensure` block, since I think that's implied, but perhaps it's worth mentioning. 
- Apologies re: the whitespace changes. Please let me know if you'd like me to resubmit with a smaller diff. 
- Documentation
- N/A
=> Example using async/http/internet/instance

examples/race/client.rb, examples/race/server.rb, lib/async/http/protocol/http1/client.rb, lib/async/http/protocol/http1/connection.rb, spec/async/http/protocol/http11/desync_spec.rb
It is possible for the HTTP/1 client to get out of sync if an exception is raised during writing the request and before finishing reading the response line. If this happens, subsequent requests will potentially read the previous response body.
- Bug fix.
=> Track HTTP/1 connection state so that we can avoid reusing it.

lib/async/http/endpoint.rb, spec/async/http/endpoint_spec.rb
When using Endpoint.parse, the generated URL is normalized before
passing to the constructor, resulting in a `path` attribute of `/` by default.
When using Endpoint.for, the path is left as an empty String, which causes
issues in some web servers. To make the behaviour consistent, Endpoint.for
will normalize as well.
=> Endpoint.for should normalize URL

lib/async/http/client.rb
Some tests are failing in CI, and the logs are very hard to debug since the output is lengthy (the log archive was 110mb zip file). This PR addresses this issue by trimming down the inspect output of `Async::HTTP::Client` to make it human readable.
=> Reduce output size of Async::HTTP::Client#inspect

lib/async/http/protocol/http2/stream.rb
Fixes https://github.com/socketry/async-http/issues/91
=> Do not require `Trailer` header to parse trailers in HTTP2

lib/async/http/relative_location.rb, spec/async/http/client_spec.rb, spec/async/http/performance_spec.rb, spec/async/http/protocol/http11/desync_spec.rb, spec/async/http/protocol/http11_spec.rb, spec/async/http/protocol/http2_spec.rb, spec/async/http/protocol/shared_examples.rb, spec/async/http/proxy_spec.rb, spec/async/http/relative_location_spec.rb, spec/async/http/retry_spec.rb, spec/async/http/server_context.rb, spec/async/http/statistics_spec.rb
The fibers scheduler introduces more context switching points which made some specs a bit flaky. This PR fixes those cases and improves the general structure of some related tests.
- Maintenance.
=> Fix test compatibility with new fiber scheduler.

lib/async/http/endpoint.rb, spec/async/http/endpoint_spec.rb
The `Endpoint.for` method can accept an optional path, overriding the default of `/`.
Continuation of #85 
- New feature.
=> Allow `Endpoint.for` to accept optional path

spec/async/http/performance_spec.rb
It seems like this might have been working on some platforms, but on macOS it was definitely failing.
https://github.com/socketry/io-event/issues/36
- Bug fix.
=> Fix performance spec - don't use container in reactor.

async-http.gemspec, config/external.yaml, lib/async/http/client.rb, spec/spec_helper.rb
The interface for `trace_context` was updated since it wasn't possible to support it on Datadog after they changed their internal code structure.
- Bug fix.
=> Test with traces enabled.

lib/async/http/relative_location.rb
Align our redirect handling with the fetch specification. See https://github.com/rack/rack/issues/1994 for more context.
- Bug fix.
- Maintenance.
=> Better redirect handling

lib/async/http/endpoint.rb, spec/async/http/body_spec.rb, spec/async/http/protocol/shared_examples.rb, spec/async/http/server_context.rb
The server context ensures that a bound endpoint is used for the server, which avoids any race between creating the server and connecting with the client.
- Bug fix.
- Maintenance.
=> Update body spec to use server context.

async-http.gemspec, lib/async/http/client.rb, lib/async/http/server.rb
The `traces` gem was updated with a "easier to use" interface, `Traces.trace`. This also prepares us to avoid clobbering `Protocol::HTTP::Methods#trace`.
- Maintenance.
=> Prefer `Traces.trace`.

lib/async/http/protocol/http1/server.rb, spec/async/http/protocol/http11_spec.rb
Previously `fail_request` wrote the initial part of the response, but failed to finish it. When tested with `Async::HTTP::Client`, this caused the client to experience an `EOFError`.
This PR causes `fail_request` to now finish the response. It also rescues exceptions that might arise from the attempt to write the response.
Before:
```
HTTP/1.1 400 Bad Request
```
After:
```
HTTP/1.1 400 Bad Request
connection: close
content-length: 0
<- required final blank line
```
- Bug fix.
=> Make fail_request properly finish the response

.mailmap, lib/async/http/body/delayed.rb
If any part of `async/http/protocol/*` is required before `Async::HTTP::Body::Delayed`, then `Delayed` cannot be loaded. This PR corrects that.
- Bug fix.
=> Fix Delayed when required after async/http/protocol/*

lib/async/http/protocol/http2/stream.rb
This PR changes one log entry from `error` to `debug` to reduce log noise. Since this exception is fully handled by resetting the stream, using `error` seems unnecessary.
- Maintenance.
=> Downgrade log level

lib/async/http/protocol/http1/response.rb, test/async/http/protocol/http11.rb
Save away the raw reason phrase provided by the server. This is of limited niche value, as the reason phrase seems to be _mostly_ unused/ignored.
One example of where it's needed:
The [Proxmox VE API](https://pve.proxmox.com/wiki/Proxmox_VE_API) ships error reason strings back using the HTTP reason phrase. Without this side-channel, error status is 100% opaque/unavailable.
See (very brief) discussion: https://github.com/socketry/async-http/discussions/145
It's probably not worth overthinking this, but some other thoughts that came to mind were:
* Does it make sense to define a reason accessor in other HTTP version responses so the method is always available?
* My opinion: no, not worth it and feels pretty bad to burden other versions of HTTP with this detail when it's nearly irrelevant.
* …
=> Save reason phrase in Protocol::HTTP1::Response

async-http.gemspec, fixtures/async/http/a_protocol.rb, gems.rb, lib/async/http/protocol/http1/request.rb, lib/async/http/protocol/http1/response.rb, lib/async/http/protocol/http2/request.rb, lib/async/http/protocol/http2/response.rb, lib/async/http/protocol/http2/stream.rb, lib/async/http/protocol/request.rb
While informational responses are not particularly popular, we should at least ignore them. Later, we may expose them to the user.
- Bug fix.
=> Ignore non-final responses.

lib/async/http/protocol/http1/server.rb
This PR includes 2 related items:
1. Fixes an old regression where `request = nil` should be conditional upon the _request_ body, but was incorrectly the _response_ body. Looking at the git history, the original behavior was `... unless request.body` and was changed in b3cc9ce, seemingly accidentally during a refactor.
I occasionally experience random hangs when running my test suite and believe this might be one cause of them.
2. Changes the handling of unconsumed bodies from `request.finish` to `request.each{}`. 
`finish` buffers the request fully in memory as a `Buffered`, causing needless memory bloat in the ruby process. Using `each` skips the buffering, but is otherwise behaves the same.
- Bug fix.
=> Improve handling of unconsumed request bodies at end of http1 requests

lib/async/http/endpoint.rb
Require shared endpoint by default to reduce pain in migrating to `io-endpoint`.
- Maintenance.
=> Require shared endpoint by default.

lib/async/http/protocol/http1/server.rb, lib/async/http/protocol/http2/connection.rb, lib/async/http/protocol/http2/server.rb
Add support for `defer_stop` for graceful shutdown. These changes are necessary but I'm not sure if they are sufficient - more experimentation is required to see the exact impact to client behaviour.
See <https://github.com/socketry/falcon/issues/71> for more details.
- New feature.
=> Defer stop

async-http.gemspec, lib/async/http/protocol/http1/connection.rb, lib/async/http/protocol/http1/server.rb, test/async/http/protocol/http11.rb
Whenever the application performs hijacking of http/1.1 connection, the server must not attempt to send any response back to the client. Prior to this change, it was not the case due to imprecise check and has led to an error being logged (the real issue occurred during an attempt to write to a stream that was set to nil, but that's really just a symptom).
The proposed fix simply adds a flag to the connection object so that it is aware of the fact the underlying stream no longer belongs to it and must not be used to send any data over.
- Bug fix.
=> Avoid writing to the body after full hijack

async-http.gemspec, bake/async/http/h2spec.rb, config/external.yaml, examples/google/codeotaku.rb, examples/google/search.rb, fixtures/async/http/a_protocol.rb, gems.rb, lib/async/http/body/pipe.rb, lib/async/http/client.rb, lib/async/http/endpoint.rb, lib/async/http/protocol/http1.rb, lib/async/http/protocol/http1/connection.rb, lib/async/http/protocol/http1/request.rb, lib/async/http/protocol/http10.rb, lib/async/http/protocol/http11.rb, lib/async/http/protocol/http2.rb, lib/async/http/protocol/http2/connection.rb, lib/async/http/proxy.rb, lib/async/http/server.rb, test/async/http/body.rb, test/async/http/body/pipe.rb, test/async/http/endpoint.rb, test/async/http/proxy.rb, test/async/http/ssl.rb
Remove the `async-io` dependency.
- `Async::IO::Endpoint` is replaced by `IO::Endpoint`: https://github.com/socketry/io-endpoint
- Ruby 3.1 won't be fully supported due to lack of `IO#timeout` support.
- We require a large number of bug fixes in <https://github.com/ruby/openssl/issues/741>.
- Performance improvement.
- Maintenance.
=> Replace `Async::IO` with native `IO`.

lib/async/http/server.rb, test/async/http/server.rb
`::IO::Endpoint` returns bare fibers, and we need to wait on them. Change `Async::Server#run` to return a single task which can be waited on.
- Bug fix.
- Breaking change.
=> Let's be more specific w.r.t. `Async::HTTP::Server#run`.

async-http.gemspec, lib/async/http/endpoint.rb, lib/async/http/protocol/http.rb, lib/async/http/protocol/http1.rb, lib/async/http/protocol/http10.rb, lib/async/http/protocol/http11.rb, lib/async/http/protocol/http2.rb, test/async/http/endpoint.rb, test/async/http/protocol/http.rb
This PR adds `Async::HTTP::Protocol::HTTP` which auto-detects HTTP1 vs HTTP2 for inbound (server) connections. It is comparable to `Async::HTTP::Protocol::HTTPS`, just for http:// instead.
It uses HTTP/2 Connection Preface detection, outlined in the [HTTP/2 RFC](https://www.rfc-editor.org/rfc/rfc9113.html#section-3.4).
This is only for server connections. Protocol::HTTP's client always uses HTTP1 as there is no present facility in the RFC for auto-detection for clients using http://. (There was some language around Upgrade: h2c in earlier RFC versions, but it has since been removed.)
<details>
<summary><h4><del>Note on HTTP/1.0</del></h4></summary>
~~HTTP/1.0 requests have the potential to be too short to be properly detected. This is expected behavior, and is treated no differently than …
=> Add auto-detection of HTTP1 vs HTTP2 for inbound http:// connections

lib/async/http/endpoint.rb, lib/async/http/internet.rb, test/async/http/internet.rb
This PR introduces changes that allow passing custom `Async::HTTP::Endpoint` to `Async::HTTP::Internet`. This could be useful for example when we need to provide custom SSL options to requests.
=> Allow using custom endpoints for Async::HTTP::Internet

lib/async/http/endpoint.rb, test/async/http/internet.rb
`URI::HTTP` objects do not define a `to_str` method, so call `to_s` on the `uri` instead.
- Bug fix.
=> Allow `Async::HTTP::Internet` methods to accept `URI::HTTP` objects.

guides/links.yaml, guides/mocking/readme.md, lib/async/http.rb, lib/async/http/mock.rb, lib/async/http/mock/endpoint.rb, test/async/http/mock.rb
This provides some basic building blocks for mocking up `Async::HTTP::Client` in the same process.
https://github.com/socketry/async-http/issues/35
=> Support for mocked client requests.

lib/async/http/endpoint.rb, test/async/http/endpoint.rb
Let's not support schemes that don't make sense. In addition, when we encounter a scheme we don't recognize, throw a reasonable error.
Fixes <https://github.com/socketry/async-http/issues/165>.
- Bug fix.
=> Specific schemes

lib/async/http/protocol/http1/response.rb
HTTP/1 response upgrade header should only have a single value.
- Maintenance.
=> Response protocol should only be a single value.

lib/async/http/relative_location.rb, test/async/http/relative_location.rb
Fixes <https://github.com/socketry/async-http/issues/171>.
- New feature.
- Maintenance.
=> Extract redirect location handling and clarify behaviour.

lib/async/http/middleware/location_redirector.rb, lib/async/http/relative_location.rb, test/async/http/middleware/location_redirector.rb
The scope of the implementation has changed.
- Maintenance.
=> Move `Async::HTTP::RelativeLocation` to `Async::HTTP::Middleware::LocationRedirector`.

lib/async/http/protocol/http1/connection.rb, lib/async/http/protocol/http2/connection.rb, lib/async/http/protocol/peer.rb, lib/async/http/protocol/request.rb, lib/async/http/protocol/response.rb, lib/async/http/server.rb
It turns out that `Addrinfo#ip_address` is slow. Let's cache it, since most connections will handle more than one request.
- New feature.
=> Expose cached peer address interface.

lib/async/http/internet/instance.rb, releases.md
Fix the inconsistencies as outlined in <https://github.com/socketry/async-http/issues/190>.
- Bug fix.
=> Pass through *arguments and **options for consistency.

async-http.gemspec, lib/async/http/protocol/http2/output.rb, lib/async/http/protocol/http2/request.rb, lib/async/http/protocol/http2/response.rb, lib/async/http/protocol/http2/stream.rb
Remove the unused support for HTTP/2 priority. This mainly affects `send_headers`, but there were no actual usage of setting the priority, so the impact is effectively zero.
- Maintenance.
=> Remove support for HTTP/2 priority.

lib/async/http/protocol/configurable.rb, lib/async/http/protocol/defaulton.rb, lib/async/http/protocol/http.rb, lib/async/http/protocol/http1.rb, lib/async/http/protocol/http1/connection.rb, lib/async/http/protocol/http10.rb, lib/async/http/protocol/http11.rb, lib/async/http/protocol/http2.rb, lib/async/http/protocol/http2/connection.rb, lib/async/http/protocol/https.rb, releases.md, test/async/http/protocol/http.rb, test/async/http/protocol/http1.rb, test/async/http/protocol/https.rb
Allow passing through configuration to protocol / connection classes.
- New feature.
=> Allow passing through configuration to underlying protocol.

lib/async/http/protocol/http1/server.rb, lib/async/http/protocol/http2/connection.rb
```
async-http-0.86.0/lib/async/http/protocol/http1/server.rb:55: warning: assigned but unused variable - error
async-http-0.86.0/lib/async/http/protocol/http2/connection.rb:99: warning: assigned but unused variable - ignored_error
```
=> Fix unused variable warnings

fixtures/async/http/a_protocol.rb
Tempfile uses a finalizer that calls `unlink` which can be offloaded, and can be cancelled, resulting in the following log:
```
describe Async::HTTP::Protocol::HTTP10 it behaves like a protocol with multiple client requests
describe Async::HTTP::Protocol::HTTP10 it behaves like a protocol with multiple client requests it doesn't cancel all requests test/async/http/protocol/http10.rb:10:575
/home/samuel/.gem/ruby/3.4.0/gems/console-1.31.0/lib/console/filter.rb:169: warning: Exception in finalizer #<Tempfile::FinalizerManager:0x00007f5354070d38 @open_files={}, @path="/tmp/20250713-47323-4bqv5i", @pid=47323, @unlinked=false>
/home/samuel/Developer/socketry/async/lib/async/scheduler.rb:244:in 'IO::Event::Selector::URing#transfer': Async::Stop (Async::Stop)
from …
```
=> Don't leak Tempfile instances.

readme.md
This PR fixed the description of  README because this gem hasn't depended on `async-io` since #147.
- Docs
=> Fix the description of README

test/async/http/client/google.rb
Running `sus test/async/http/client/google.rb` results in 1 test error:
```ruby
describe Async::HTTP::Client it can request remote resource with compression test/async/http/client/google.rb:35
expect #<Async::HTTP::Protocol::HTTP2::Response:0xa50 status=200> to
be success?
✓ assertion passed test/async/http/client/google.rb:40
⚠ NameError: uninitialized constant Async::HTTP::Body::Inflate
test/async/http/client/google.rb:42 block (3 levels) in <top (required)>
```
The other test files are OK.
=> Fix uninitialized constant in test.
